import json
from typing import List, Dict, Any

class DataSchemaManager:
    """
    Handles the serialization and persistence of synthetic data into formats 
    required by modern fine-tuning frameworks (SFT/DPO).
    """
    def save_synthetic_data(self, data_list: List[Dict[str, Any]], format_type: str) -> None:
        """
        Writes the list of structured interaction dictionaries to a JSONL file.

        Args:
            data_list: The list of synthetic records generated by SyntheticDataGenerator.
            format_type: Specifies the output format ("SFT" or "DPO").
        """
        if not data_list:
            print("No data provided to save.")
            return

        filename = f"synthetic_training_data_{format_type}_{json.dumps(data_list[0]['prompt'])[:20]}.jsonl"
        output_path = "data/" + filename # Saving it in the data directory for visibility

        print(f"Saving {len(data_list)} records to {output_path} using {format_type} format.")

        with open(output_path, 'w', encoding='utf-8') as f:
            for record in data_list:
                if format_type == "DPO":
                    # DPO requires a specific structure for chosen/rejected pairs
                    record_to_write = {
                        "prompt": record["prompt"],
                        "chosen_response": record.get("chosen_response", ""),
                        "rejected_response": record.get("rejected_response", "")
                    }
                elif format_type == "SFT":
                    # SFT requires a simple prompt/completion pair
                    record_to_write = {
                        "prompt": record["prompt"],
                        "completion": record.get("chosen_response", "") # Using chosen as the ideal completion
                    }
                else:
                    continue

                f.write(json.dumps(record_to_write) + '\n')
        
        print(f"Successfully wrote {len(data_list)} records to disk.")

# ...existing code...