"""VIKI v2 — Next-generation OS agent architecture."""

from .agents import (
    ActionPlan,
    AgentFindings,
    AgentManager,
    AgentResult,
    ArchitectAgent,
    DataAgent,
    DeveloperAgent,
    DevOpsAgent,
    QAAgent,
    ResearchAgent,
    SecurityAgent,
    SpecialistAgent,
)
from .config import (
    DataConfig,
    LLMConfig,
    MemoryConfig,
    ToolsConfig,
    UIConfig,
    V2Config,
    get_config,
    load_config,
    parse_cli_overrides,
    set_config,
    watch_config,
)
from .core import (
    AgentResponse,
    ContextBuilder,
    ContextManager,
    CoreAgent,
    CritiqueIssue,
    CritiqueLevel,
    CritiqueResult,
    ExecutionReport,
    IntentAnalyzer,
    IntentResult,
    PermissionCheck,
    PermissionManager,
    PermissionTier,
    RepoAnalyzer,
    RepositoryProfile,
    ResponseGenerator,
    SelfCritique,
    Session,
    SessionManager,
    StepResult,
    TaskPlan,
    TaskPlanner,
    TaskStep,
    ToolSelector,
    Turn,
)
from .memory import (
    Decision,
    LongTermMemory,
    ProjectInfo,
    ProjectMemory,
    SessionMemory,
)
from .providers import create_provider
from .providers.base import SystemProvider
from .tools import (
    BaseTool,
    DatabaseTool,
    DevTool,
    FileSystemTool,
    GitTool,
    NetworkTool,
    ShellTool,
    SystemTool,
    ToolRegistry,
    ToolResult,
)
from .tools.mcp import (
    MCPTool,
    V2MCPClient,
    load_mcp_config,
    register_mcp_tools,
    register_mcp_tools_async,
)
from .workflow.definitions import BUILTIN_WORKFLOWS, get_workflow, list_workflows
from .workflow.engine import RollbackStep, Workflow, WorkflowEngine, WorkflowResult, WorkflowStep

__all__ = [
    # Providers
    "SystemProvider",
    "create_provider",
    # Config
    "V2Config",
    "LLMConfig",
    "MemoryConfig",
    "ToolsConfig",
    "UIConfig",
    "DataConfig",
    "get_config",
    "load_config",
    "set_config",
    "parse_cli_overrides",
    "watch_config",
    # Tools
    "BaseTool",
    "ToolResult",
    "ToolRegistry",
    "SystemTool",
    "NetworkTool",
    "FileSystemTool",
    "ShellTool",
    "GitTool",
    "DatabaseTool",
    "DevTool",
    # MCP
    "V2MCPClient",
    "MCPTool",
    "load_mcp_config",
    "register_mcp_tools",
    "register_mcp_tools_async",
    # Core
    "CoreAgent",
    "AgentResponse",
    "IntentAnalyzer",
    "IntentResult",
    "ToolSelector",
    "PermissionTier",
    "PermissionCheck",
    "PermissionManager",
    "ContextBuilder",
    "ContextManager",
    "ResponseGenerator",
    "SessionManager",
    "Session",
    "Turn",
    "SelfCritique",
    "CritiqueIssue",
    "CritiqueLevel",
    "CritiqueResult",
    "TaskPlanner",
    "TaskPlan",
    "TaskStep",
    "StepResult",
    "ExecutionReport",
    "RepoAnalyzer",
    "RepositoryProfile",
    # Memory
    "SessionMemory",
    "ProjectMemory",
    "ProjectInfo",
    "Decision",
    "LongTermMemory",
    # Agents
    "SpecialistAgent",
    "AgentFindings",
    "AgentResult",
    "ActionPlan",
    "AgentManager",
    "ArchitectAgent",
    "DeveloperAgent",
    "SecurityAgent",
    "ResearchAgent",
    "DevOpsAgent",
    "DataAgent",
    "QAAgent",
    # Workflow
    "Workflow",
    "WorkflowStep",
    "WorkflowResult",
    "WorkflowEngine",
    "RollbackStep",
    "BUILTIN_WORKFLOWS",
    "get_workflow",
    "list_workflows",
]
